routes/authentication_controller.py
# app/routes/authentication_controller.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user
from ..classes.user_class import User
from flasgger import swag_from

# url_prefix='/authentication'
app = Blueprint('authentication_controller', __name__)

@app.route('/login', methods=['GET'])
@swag_from({
    'parameters': [],
    'responses': {
        200: {
            'description': 'Login page',
            'schema': {
                'type': 'string',
                'example': 'HTML content of the login page'
            }
        }
    }
}, methods=['GET'])
def login_get():
    """
    Login
    """
    if current_user.is_authenticated:
            return redirect(url_for('booking_controller.index'))
    return render_template('login.html')

@app.route('/login', methods=['POST'])
@swag_from({
    'parameters': [
        {
            'name': 'username',
            'in': 'formData',
            'type': 'string',
            'required': True,
            'description': 'The username of the user'
        },
        {
            'name': 'password',
            'in': 'formData',
            'type': 'string',
            'required': True,
            'description': 'The password of the user'
        }
    ],
    'responses': {
        200: {
            'description': 'A single user item',
            'schema': {
                'id': 'User',
                'properties': {
                    'username': {
                        'type': 'string',
                        'description': 'The name of the user',
                        'default': 'John Doe'
                    }
                }
            }
        }
    }
}, methods=['POST'])
def login_post():
    """
    Login
    """
    if current_user.is_authenticated:
            return redirect(url_for('booking_controller.index'))
                        
    username = request.form['username']
    password = request.form['password']
    result = User.get_user_by_username(username)
    if result['status'] == 'found':
        if result and result['result'].password == password:
            login_user(result['result'])
            User.update_user(result['result'].user_id, 'is_authenticated', True)
            return redirect(url_for('booking_controller.index'))
        flash('Invalid username or password')
    else:
        flash(result['message'])

@app.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('authentication_controller.login'))

@app.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
            return redirect(url_for('booking_controller.index'))
    
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        result = User.create_new_user(username, password)
        if result['status'] == 'created':
            flash('User registered successfully')
        else:
            flash(result['message'])
        return redirect(url_for('authentication_controller.login'))
    return render_template('register.html')

routes/booking_controller.py
# booking_form_blueprint.py
from ..classes.booking_class import *
from flask import Blueprint, request, jsonify, render_template, redirect
from flask_login import login_required
app = Blueprint('booking_controller', __name__)

# prefix = "/bookings"

# route '/'
# [GET]
@app.route('/', methods=['GET'])
@login_required
def index():
    """Return the booking form."""
    return redirect('/mybookings/form')

# route '/mybookings'
# [GET]
@app.route('/mybookings', methods=['GET'])
@login_required
def get_all_bookings():
    """Return all user's bookings."""
    return get_all_bookings()

# route '/mybookings/form'
@app.route('/mybookings/form', methods=['GET'])
@login_required
def get_booking_form():
    return render_template('booking_form.html', title='Booking Form')

# [POST]
@app.route("/mybookings/form", methods=["POST"])
@login_required
def add_booking():
    if request.is_json:
        booking_data = request.get_json()
        booking = booking.from_dict(booking_data)
        return add_booking(booking)
    return {"error": "Request must be JSON"}, 415

# route '/mybookings/filter'
# [GET]
@app.route("/mybookings/filter", methods=["GET"])
@login_required
def filter_bookings():
    args = []
    for request_arg in request.args:
        args.append({'name': request_arg, 'value': request.args.get(request_arg)})
    return get_booking_with_args(args)


# route '/mybookings/<booking_id>'
# [GET]
@app.route("/mybookings/<booking_id>", methods=["GET"])
@login_required
def get_booking(booking_id):
    return get_booking_with_args({'name': 'id', 'value': booking_id})

if __name__ == "__main__":
    app.run(debug=True)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    <icon rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
</head>
<body>
    <div>
        <!-- Jinja directives: page contents will go between them -->
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul class="flashes">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/booking_form.html
{% extends 'base.html' %}

{% block content %}

<h1>List of products</h1>

<!-- pairs is a list that must be sent here by a route function The list will contain 45 pairs: a presidency number, and a president's name -->

<ul>
    {% for product in products %}
    <li>{{ product['id'] }},{{ product['name'] }},{{ product['price'] }},{{ product['category'] }}</li>
    {% endfor %}
</ul>

{% endblock %}

templates/index copy.html
{% extends 'base.html' %}

{% block content %}

<h1>Welcome to the booking system</h1>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Welcome to the booking system</h1>

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}

<h1>Welcome to the booking system</h1>

<form method="POST" action="/login">
    <div>
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
    </div>
    <div>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
    </div>
    <div>
        <button type="submit">Login</button>
    </div>
</form>

{% endblock %}

templates/mybookings.html
{% extends 'base.html' %}

{% block content %}

<h1>List of bookings</h1>

<!-- pairs is a list that must be sent here by a route function The list will contain 45 pairs: a presidency number, and a president's name -->

<ul>
    {% for booking in bookings %}
    <li>{{ booking['id'] }},{{ booking['user'] }},{{ booking['date'] }},{{ booking['category'] }}</li>
    {% endfor %}
</ul>

{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block title %}Login Page{% endblock %}

{% block content %}

<h1>Register</h1>

<form method="POST" action="{{ url_for('authentication_controller.register') }}">
    <div>
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
    </div>
    <div>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
    </div>
    <div>
        <button type="submit">Register</button>
    </div>
</form>

{% endblock %}